routes/web.php
<?php

use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\ContactoFormController;
use App\Http\Controllers\EstadoController;
use App\Http\Controllers\MinimoCompraController;
use App\Http\Controllers\PedidoController;
use App\Http\Controllers\ProductoController;
use App\Http\Controllers\RecetaController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UsuarioController;
use App\Models\Usuario;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);

    Route::get('productos/filter',[ ProductoController::class, 'filter'])->name('productos.filter.get');
    Route::resource('productos', ProductoController::class)->names('productos');
    Route::post('productos/filter',[ ProductoController::class, 'filter'])->name('productos.filter');
    Route::resource('categorias', CategoriaController::class )->names('categorias');
    Route::post('categorias/filter',[ CategoriaController::class, 'filter'])->name('categorias.filter');
    Route::resource('recetas', RecetaController::class )->names('recetas');
    Route::post('recetas/filter',[ RecetaController::class, 'filter'])->name('recetas.filter');
    Route::resource('usuarios', UsuarioController::class )->names('usuarios');
    Route::post('usuarios/filter',[ UsuarioController::class, 'filter'])->name('usuarios.filter');
    Route::resource('consultas', ContactoFormController::class )->parameters(['consultas' => 'contacto',])->names('consultas');
    Route::post('consultas/filter',[ ContactoFormController::class, 'filter'])->name('consultas.filter');
    Route::get('pedidos/filter',[ PedidoController::class, 'filter'])->name('pedidos.filter.get');
    Route::resource('pedidos', PedidoController::class )->names('pedidos');
    Route::get('pedidos/excel/download/productos/{id}', [ PedidoController::class, 'exportItem'])->name('pedidos.excelItem');
    Route::get('pedidos/excel/download/{days?}/{state?}/{tiposUsuario?}', [ PedidoController::class, 'export'])->where('days', '[0-9]+')->name('pedidos.excel');
    Route::post('pedidos/filter',[ PedidoController::class, 'filter'])->name('pedidos.filter');

    Route::resource('estados', EstadoController::class );
    Route::post('estados/filter',[ EstadoController::class, 'filter'])->name('estados.filter');

	Route::resource('minimo', MinimoCompraController::class)->names('minimo');
    Route::post('minimo/filter',[ MinimoCompraController::class, 'filter'])->name('minimo.filter');


    Route::get('usuario/load', [UsuarioController::class, 'loadAddress']);
});

app/Models/Usuario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Usuario extends Model
{
    use HasFactory, Sortable;
    const CREATED_AT = 'fecha_creado';
    const UPDATED_AT = 'fecha_modif';
    protected $fillable = ['tipo_usuario_id', 'nombre', 'apellido', 'email', 'dni',
	 'password', 'telefono',
	 'direccion', 'latitud',
	 'longitud', 'estado',
	 'calle_nro', 'nombre_calle',
	 'localidad',  'partido',
	 'provincia', 'pais',
	 'codigo_postal'
	 , 'direccion2', 'barrio'
	];
    protected $sortable = ['tipo_usuario_id', 'nombre', 'apellido', 'email', 'dni',
	 'password', 'telefono', 'direccion', 'latitud', 'longitud', 'estado',
	 'calle_nro', 'nombre_calle',
	 'localidad',  'partido',
	 'provincia', 'pais','direccion2', 'barrio',
	 'codigo_postal'];
	 protected $appends = ['full_address'];

    public function tipoUsuario(){
        return $this->belongsTo(TipoUsuario::class, 'tipo_usuario_id');
    }
    public function Pedidos(){
        return $this->hasMany(Pedido::class, 'cli_id');
    }

	public function getFullAddressAttribute(){
		$fullAddress = '';
		if ($this->longitud != 0 && $this->latitud != 0) {
			if ($this->localidad ) {
				$fullAddress = $this->nombre_calle.' '.$this->calle_nro.', '.$this->partido.', '.$this->provincia .', '.$this->pais ;
			}else {
				$fullAddress = $this->nombre_calle.' '.$this->calle_nro.', '.$this->localidad.', '.$this->partido.', '.$this->provincia .', '.$this->pais ;
			}
		}
		return $fullAddress;

	}
}

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUsuarioRequest;
use App\Http\Requests\UpdateUsuarioRequest;
use App\Models\TipoUsuario;
use App\Models\Usuario;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

class UsuarioController extends Controller
{
	function __construct()
	{
		$this->middleware('permission:user-list|user-create|user-edit|user-delete', ['only' => ['index', 'store', 'filter']]);
		$this->middleware('permission:user-create', ['only' => ['create', 'store']]);
		$this->middleware('permission:user-edit', ['only' => ['edit', 'update']]);
		$this->middleware('permission:user-delete', ['only' => ['destroy']]);
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		$usuarios = Usuario::sortable()
			->orderBy('fecha_modif', 'Desc')
			->paginate(5);

		return view('usuario.index', compact('usuarios'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		$tipoUsuario = TipoUsuario::all();
		return view('usuario.create', compact('tipoUsuario'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(StoreUsuarioRequest $request)
	{
		$merged = [];
		$merged['password'] = 123456;
		Usuario::create(array_merge($request->all(), $merged));
		return redirect()
			->route('usuarios.index')
			->with('success', 'Se creo correctamente el usuario');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show(Usuario $usuario)
	{
		return view('usuario.show', compact('usuario'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit(Usuario $usuario)
	{
		$tipoUsuario = TipoUsuario::all();
		return view('usuario.update', compact('usuario', 'tipoUsuario'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(UpdateUsuarioRequest $request, Usuario $usuario)
	{
		if (asset($request->password)) {
			unset($request['password']);
		}
		$usuario->update($request->all());
		return redirect()
			->route('usuarios.index')
			->with('success', 'Se ha actualizado correctamente el usuario.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy(Usuario $usuario)
	{
		$usuario->delete();
		return redirect()
			->route('usuarios.index')
			->with('success', 'Se ha borrado correctamente el usuario.');
	}
	public function filter(Request $request)
	{
		$usuarios =  Usuario::sortable()->where('nombre', 'like', '%' . $request->nombre . '%')
			->orWhere('apellido', 'like', '%' . $request->nombre . '%')
			->orWhere('email', 'like', '%' . $request->nombre . '%')
			->get();

		return view('usuario.index', compact('usuarios'));
	}
	/* helper */
	public function loadAddress()
	{

		$googleKey = 'AIzaSyDVY3YmApJPaBZqmG627e9XUx_5n3f502o.';
		$url = 'https://maps.googleapis.com/maps/api/geocode/json?latlng=';
		$usuarios = Usuario::where('latitud', '!=', 0)->where('longitud', '!=', 0)
		->where('calle_nro', null )
		->where('nombre_calle', null)
		->where('localidad', null)
		->where('partido', null)
		->where('provincia', null)
		->where('pais', null)
		->where('codigo_postal', null)
		->get();
		foreach ($usuarios as $usuario){
			$googleUrl = $url.$usuario->latitud.','.$usuario->longitud.'&key='.$googleKey;
			$http = Http::get($googleUrl);
			$json = $http->json();
			dd(	$googleUrl, $json);
			$addresses = $json['results'][0]['address_components'];
			foreach ($addresses as $address) {
				switch ($address['types'][0]) {
					case 'street_number':
						$usuario->calle_nro = $address['long_name'];
						break;
					case 'route':
					case 'establishment':
						$usuario->nombre_calle = $address['long_name'];
						break;
					case 'locality':
						$usuario->localidad = $address['long_name'];
						break;
					case 'administrative_area_level_1':
						$usuario->provincia = $address['short_name'];
						break;
					case 'administrative_area_level_2':
						$usuario->partido = $address['long_name'];
						break;
					case 'country':
						$usuario->pais = $address['long_name'];
						break;
					case 'postal_code':
						$usuario->codigo_postal = $address['long_name'];
						break;
					case 'postal_code_suffix':

						break;
				}
			}
			$usuario->update();
			sleep(1);
		}
	}
}

resources/views/usuario/create.blade.php
@extends('form.index')
@section('title', 'Crear Usuario.')
@section('title-form', 'Crear usuario.')
@section('route-form', route('usuarios.store'))
@section('content-form')
    <div class="form-row">
        <div class="form-group col-lg-4 ">
            <label for="nombre">Nombre</label>
            <input type="text" class="form-control" id="nombre" name="nombre" aria-describedby='title-feedback'
                value="{{ old('nombre') }}">
            @error('nombre')
                <div id="title-feedback" class="is-invalid ">
                    <small class="text-danger">*{{ $message }}</small>
                </div>
            @enderror
        </div>
        <div class="form-group col-lg-4 pl-0">
            <label for="apellido">Apellido</label>
            <input type="text" class="form-control" id="apellido" name="apellido" aria-describedby='title-feedback'
                value="{{ old('apellido') }}">
            @error('apellido')
                <div id="title-feedback" class="is-invalid ">
                    <small class="text-danger">*{{ $message }}</small>
                </div>
            @enderror
        </div>
    </div>
    <div class="form-group col-lg-4 pl-0">
		<label for="email">email</label>
		<input type="email" class="form-control" id="email" name="email" aria-describedby='title-feedback'
			value="{{ old('email') }}" >
		@error('email')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
    <div class="form-group col-lg-4 pl-0">
		<label for="telefono">telefono</label>
		<input type="text" class="form-control" id="telefono" name="telefono" aria-describedby='title-feedback'
			value="{{ old('telefono') }}" >
		@error('telefono')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	{{-- <div class="form-group col-lg-4 pl-0">
		<label for="password">Contraseña</label>
		<input type="password" class="form-control" id="password" name="password" aria-describedby='title-feedback'
			value="{{ old('password') }}" >
		@error('password')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="password_confirmation">repetir Contraseña</label>
		<input type="password" class="form-control" id="password_confirmation" name="password_confirmation" aria-describedby='title-feedback'
			value="{{ old('password_confirmation') }}" >
		@error('password_confirmation')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div> --}}

    <div class="form-group col-lg-4 pl-0">
		<label for="email">Tipo de usuario</label>

        <select name="tipo_usuario_id" id="tipo_usuario_id" class="form-control" required>
            <option selected disabled  >Selecciona tipo de usuario</option>
            @foreach ($tipoUsuario as $tipo)
                <option value="{{$tipo->id}}" {{ old('tipo_usuario_id') == $tipo->id ? 'selected' : '' }}>{{$tipo->descripcion}}</option>
            @endforeach
        </select>
    </div>
    <div class="form-group col-lg-8 pl-0">
		<div class="custom-control custom-switch">
            <input type="checkbox" class="custom-control-input" id="estado" value="1" {{ old('estado') ==1 ? 'checked' : '' }} name="estado">
			<label class="custom-control-label" for="estado">Usuario Activo</label>
		</div>
	</div>
	<button type="submit" class="btn btn-success mb-1">Crear usuario</button>
@endsection

resources/views/usuario/index.blade.php
@extends('layouts.layout')
@section('title', 'Pagina de Usuarios')
@section('content')
	<div class="row justify-content-center">
		@if ($message = Session::get('success'))
			<div class=" col-6  mt-2 alert alert-success">
				<p>{{ $message }}</p>
			</div>
		@endif

	</div>
	<div class="row justify-content-between m-3">
		<div class="col-lg-3 offset-1">
			<h2 class="font-color-gergal">Usuarios</h2>
		</div>
		<div class="col-lg-3 offset-3">
			<form action="{{ route('usuarios.filter') }}" method="POST">
				@csrf
				<div class="input-group ">
					<input type="text" class="form-control"  name="nombre"
						placeholder="Filtrar por nombre, apellido o email" required>
					<div class="input-group-append">
						<button class="btn btn-gray " type="submit">Filtrar</button>
					</div>
				</div>
			</form>
		</div>
		@can('user-create')
			<div class="col-lg-2">
				<a href="{{ route('usuarios.create') }}" type="button" class="btn btn-success-gergal">Crear usuario</a>
			</div>
		@endcan
	</div>
	<div class="row justify-content-center">
		<div class="col-12 col-xl-10 table-responsive">
			@if ($usuarios->isEmpty())
				<p class="lead">No se tiene usuarios registrados.</p>
			@else
				<table class="table table-bordered">
					<thead>
						@if ( !method_exists($usuarios, 'render') )
							<th scope="col">Correo electronico</th>
							<th scope="col">nombre</th>
							<th scope="col">apellido</th>
							<th scope="col">Tipo de usuario</th>
							<th scope="col">Activo</th>
						@else
							<th scope="col">@sortablelink('email', 'Correo electronico')</th>
							<th scope="col">@sortablelink('nombre', 'nombre')</th>
							<th scope="col">@sortablelink('apellido', 'apellido')</th>
							<th scope="col">@sortablelink('tipo_usuario_id', 'Tipo de usuario')</th>
							<th scope="col">@sortablelink('estado', 'Activo')</th>
						@endif
						<th scope="col"></th>
					</thead>
					<tbody>
						@foreach ($usuarios as $usuario)
							<tr>
								<td> <a href="{{ route('usuarios.show', $usuario->id) }}">{{ $usuario->email }}</a> </td>
								<td>{{ $usuario->nombre }}</td>
								<td>{{ $usuario->apellido }}</td>
								<td>{{ $usuario->tipoUsuario->descripcion }}</td>
								<td>{{ $usuario->estado ? 'Si' : 'No' }}</td>


								<td>
									@can('user-edit')
										<a href="{{ route('usuarios.edit', $usuario->id) }}" type="button"
											class="btn btn-outline-primary btn-sm  my-1"> <i class="fas fa-edit"></i></a>
									@endcan
									@can('user-delete')
										<form name="form-delete" action="{{ route('usuarios.destroy', $usuario->id) }}" method="POST">
											@csrf
											@method('DELETE')
											<button type="submit" class="btn btn-outline-danger btn-sm" disabled><i class="fas fa-trash-alt"></i></button>
										</form>
									@endcan

								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			@endif
            {{ method_exists($usuarios, 'appends') ? $usuarios->appends(\Request::except('page'))->render() : '' }}


		</div>

	</div>


@endsection
<script src="{{ asset('js/delete.js') }}" defer></script>

resources/views/usuario/show.blade.php
@extends('layouts.layout')
@section('title', $usuario->nombre)
@section('content')
	<div class="row  m-3">
		<div class="col-4 offset-1">
			<h2>{{  $usuario->nombre .' '.$usuario->apellido }}</h2>
		</div>

	</div>

	<div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Email: {{  $usuario->email }}
			</p>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Teléfono: {{ $usuario->telefono }}
			</p>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Dirección: {{ $usuario->direccion }}
			</p>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Latitud: {{ $usuario->latitud }}
			</p>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Longitud: {{ $usuario->longitud }}
			</p>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Tipo de usuario: {{ $usuario->tipoUsuario->descripcion }}
			</p>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Activo: {{ $usuario->estado ? 'Si' : 'No' }}
			</p>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-8 ">
			<div class="accordion" >
				<div class="card">
					<div class="card-header" >
					  <h2 class="mb-0" >
						<button id="accordionParent" onclick=" return collapse();" class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
							PEDIDOS
						</button>
					  </h2>
					</div>
					<div  class="collapse" aria-labelledby="headingOne" data-parent="accordionParent" >
						@if ($usuario->pedidos->isEmpty())
							<p class="lead pl-3">Sin pedidos</p>

						@else
							<div class="accordion ml-3" id="accordionExample">
								@foreach ($usuario->pedidos as $pedido)

								<div class="card">
								<div class="card-header" >
									<h2 class="mb-0" >

									<button id="{{$pedido->id}}" onclick=" return collapse();" class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
										pedido: {{ $pedido->id }}
									</button>
									</h2>
								</div>

								<div id="collapse{{$pedido->id}}" class="collapse" aria-labelledby="headingOne" data-parent="{{$pedido->id}}" >
									<div class="card-body table-responsive">
                                        @include('order.order')
									</div>
								</div>
								</div>

								@endforeach
							</div>
                        @endif
					</div>
				</div>
			</div>

		</div>
	</div>
<script>
	function collapse(){
		const evt = arguments.callee.caller.arguments[0];
		const body =  document.querySelector(`[data-parent='${evt.target.id}']`);
		body.classList.toggle('show');

	}
</script>
@endsection

resources/views/usuario/update.blade.php
@extends('form.index')
@section('title', 'Actualizar usuario.')
@section('title-form', 'Actualizar usuario.')
@section('route-form', route('usuarios.update', $usuario->id))
@section('content-form')
	@method('PUT')
	<div class="form-row">
		<div class="form-group col-lg-4 ">
			<label for="nombre">Nombre</label>
			<input type="text" class="form-control" id="nombre" name="nombre" aria-describedby='title-feedback'
				value="{{ old('nombre',$usuario->nombre) }}">
			@error('nombre')
				<div id="title-feedback" class="is-invalid ">
					<small class="text-danger">*{{ $message }}</small>
				</div>
			@enderror
		</div>
		<div class="form-group col-lg-4 pl-0">
			<label for="apellido">Apellido</label>
			<input type="text" class="form-control" id="apellido" name="apellido" aria-describedby='title-feedback'
				value="{{ old('apellido',$usuario->apellido) }}">
			@error('apellido')
				<div id="title-feedback" class="is-invalid ">
					<small class="text-danger">*{{ $message }}</small>
				</div>
			@enderror
		</div>
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="email">email</label>
		<input type="email" class="form-control" id="email" name="email" aria-describedby='title-feedback'
			value="{{ old('email', $usuario->email) }}">
		@error('email')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="telefono">telefono</label>
		<input type="text" class="form-control" id="telefono" name="telefono" aria-describedby='title-feedback'
			value="{{ old('telefono', $usuario->telefono) }}">
		@error('telefono')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	{{-- <div class="form-group col-lg-4 pl-0">
		<label for="password">Contraseña</label>
		<input type="password" class="form-control" id="password" name="password" aria-describedby='title-feedback'
			value="{{ old('password') }}">
		@error('password')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="password_confirmation">repetir Contraseña</label>
		<input type="password" class="form-control" id="password_confirmation" name="password_confirmation"
			aria-describedby='title-feedback' value="{{ old('password_confirmation') }}">
		@error('password_confirmation')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="direccion">Dirección</label>
		<input type="text" class="form-control" id="direccion" name="direccion" aria-describedby='title-feedback'
			value="{{ old('direccion', $usuario->direccion) }}">
		@error('direccion')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-row">
		<div class="form-group col-lg-4 ">
			<label for="latitud">Latitud</label>
			<input type="text" class="form-control" id="latitud" name="latitud" aria-describedby='title-feedback'
				value="{{ old('latitud', $usuario->latitud) }}">
			@error('latitud')
				<div id="title-feedback" class="is-invalid ">
					<small class="text-danger">*{{ $message }}</small>
				</div>
			@enderror
		</div>
		<div class="form-group col-lg-4 pl-0">
			<label for="longitud">Longitud</label>
			<input type="text" class="form-control" id="longitud" name="longitud" aria-describedby='title-feedback'
				value="{{ old('longitud', $usuario->longitud) }}">
			@error('longitud')
				<div id="title-feedback" class="is-invalid ">
					<small class="text-danger">*{{ $message }}</small>
				</div>
			@enderror
		</div>
	</div> --}}
	<div class="form-group col-lg-4 pl-0">
		<label for="email">Tipo de usuario</label>
		<select name="tipo_usuario_id" id="tipo_usuario_id" class="form-control" required>
			<option selected disabled>Selecciona tipo de usuario</option>

			@foreach ($tipoUsuario as $tipo)
				<option value="{{ $tipo->id }}" {{ old('tipo_usuario_id', $usuario->tipo_usuario_id ) == $tipo->id ? 'selected' : '' }}>{{ $tipo->descripcion }}</option>
			@endforeach
		</select>
	</div>
	<div class="form-group col-lg-8 pl-0">
		<div class="custom-control custom-switch">
			<input type="checkbox" class="custom-control-input" id="estado" value="1"
				{{ old('estado', $usuario->estado) == 1 ? 'checked' : '' }} name="estado">
			<label class="custom-control-label" for="estado">Usuario Activo</label>
		</div>
	</div>
	<button type="submit" class="btn btn-success mb-1">Actualizar usuario</button>
@endsection