routes/web.php
<?php

use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\ContactoFormController;
use App\Http\Controllers\EstadoController;
use App\Http\Controllers\MinimoCompraController;
use App\Http\Controllers\PedidoController;
use App\Http\Controllers\ProductoController;
use App\Http\Controllers\RecetaController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UsuarioController;
use App\Models\Usuario;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);

    Route::get('productos/filter',[ ProductoController::class, 'filter'])->name('productos.filter.get');
    Route::resource('productos', ProductoController::class)->names('productos');
    Route::post('productos/filter',[ ProductoController::class, 'filter'])->name('productos.filter');
    Route::resource('categorias', CategoriaController::class )->names('categorias');
    Route::post('categorias/filter',[ CategoriaController::class, 'filter'])->name('categorias.filter');
    Route::resource('recetas', RecetaController::class )->names('recetas');
    Route::post('recetas/filter',[ RecetaController::class, 'filter'])->name('recetas.filter');
    Route::resource('usuarios', UsuarioController::class )->names('usuarios');
    Route::post('usuarios/filter',[ UsuarioController::class, 'filter'])->name('usuarios.filter');
    Route::resource('consultas', ContactoFormController::class )->parameters(['consultas' => 'contacto',])->names('consultas');
    Route::post('consultas/filter',[ ContactoFormController::class, 'filter'])->name('consultas.filter');
    Route::get('pedidos/filter',[ PedidoController::class, 'filter'])->name('pedidos.filter.get');
    Route::resource('pedidos', PedidoController::class )->names('pedidos');
    Route::get('pedidos/excel/download/productos/{id}', [ PedidoController::class, 'exportItem'])->name('pedidos.excelItem');
    Route::get('pedidos/excel/download/{days?}/{state?}/{tiposUsuario?}', [ PedidoController::class, 'export'])->where('days', '[0-9]+')->name('pedidos.excel');
    Route::post('pedidos/filter',[ PedidoController::class, 'filter'])->name('pedidos.filter');

    Route::resource('estados', EstadoController::class );
    Route::post('estados/filter',[ EstadoController::class, 'filter'])->name('estados.filter');

	Route::resource('minimo', MinimoCompraController::class)->names('minimo');
    Route::post('minimo/filter',[ MinimoCompraController::class, 'filter'])->name('minimo.filter');


    Route::get('usuario/load', [UsuarioController::class, 'loadAddress']);
});

resources/views/product/create.blade.php
@extends('form.index')
@section('title', 'Crear Producto.')
@section('title-form', 'Crear Producto.')
@section('route-form', route('productos.store'))
@section('content-form')
	<div class="form-group col-lg-4 pl-0">
		<label for="nombre">Nombre</label>
		<input type="text" class="form-control" id="nombre" name="nombre" aria-describedby='title-feedback'
			value="{{ old('nombre') }}">
		@error('nombre')
			<div id="nombre-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group  col-lg-8 pl-0">
		<label for="descripcion">Descripción</label>
		<textarea class="form-control" id="descripcion" name="descripcion" aria-describedby='details-feedback'
			rows="3">{{ old('descripcion') }}</textarea>
		@error('descripcion')
			<div id="descripcion-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-8 pl-0">
		<label for="propiedades">Propiedades</label>
		<textarea class="form-control" id="propiedades" name="propiedades" aria-describedby='details-feedback'
			rows="3">{{ old('propiedades') }}</textarea>
		@error('propiedades')
			<div id="propiedades-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-8 pl-0">
		<label for="info_nutricional">Información nutricional</label>
		<textarea class="form-control" id="info_nutricional" name="info_nutricional" aria-describedby='details-feedback'
			rows="3">{{ old('info_nutricional') }}</textarea>
		@error('info_nutricional')
			<div id="info_nutricional-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-8 pl-0">
		<label for="img">Imagen del producto</label>
		<input type="file" class="form-control-file" id="img" name="img">
		@error('img')
			<div id="img-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-8 pl-0">
		<label for="img_hoover">Imagen descriptiva producto</label>
		<input type="file" class="form-control-file" id="img_hoover" name="img_hoover">
		@error('img_hoover')
			<div id="img_hoover-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="categoria">Categoria</label>
		<select class="form-control" name="categoria" id="categoria" >
			<option disabled selected>--- Seleccione una categoria ---</option>
			@foreach ($categorias as $categoria)
				<option value="{{ $categoria->id }}" {{ old('categoria') == $categoria->id ? 'selected' : '' }}>{{ $categoria->nombre }}</option>
			@endforeach
		</select>
		@error('sub_categoria')
			<div id="categoria-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="sub_categoria">Sub categoria</label>
		<select class="form-control" name="sub_categoria" id="sub_categoria" >
			<option disabled selected>--- Seleccione una sub categoria ---</option>
			@foreach ($categorias as $categoria)
				<option value="{{ $categoria->id }}" {{ old('sub_categoria') == $categoria->id ? 'selected' : '' }}>{{ $categoria->nombre }}</option>
			@endforeach
		</select>
		@error('sub_categoria')
			<div id="sub_categoria-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="precio_lista">Precio de lista</label>
		<input type="string" class="form-control" id="precio_lista" name="precio_lista" aria-describedby='title-feedback'
			value="{{ old('precio_lista') }}">
		@error('precio_lista')
			<div id="precio_lista-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="precio_revendedor">Precio de revendedor</label>
		<input type="string" class="form-control" id="precio_revendedor" name="precio_revendedor"
			aria-describedby='title-feedback' value="{{ old('precio_revendedor') }}">
		@error('precio_revendedor')
			<div id="precio_revendedor-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="cantidad_en_stock">Stock</label>
		<input type="text" class="form-control" id="cantidad_en_stock" name="cantidad_en_stock" aria-describedby='title-feedback'
			value="{{ old('cantidad_en_stock') }}" >
		@error('cantidad_en_stock')
			<div id="cantidad_en_stock-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="orden">Orden</label>
		<input type="text" class="form-control" id="orden" name="orden" aria-describedby='orden-feedback'
			value="{{ old('orden', 1000) }}" >
		@error('orden')
			<div id="orden-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-8 pl-0">
		<div class="custom-control custom-switch">
            <input type="checkbox" class="custom-control-input" id="estado" value="1" {{ old('estado') ==1 ? 'checked' : '' }} name="estado">
			<label class="custom-control-label" for="estado">Listo para publicar para usuario</label>
		</div>
	</div>
	<div class="form-group col-lg-8 pl-0">
		<div class="custom-control custom-switch">
            <input type="checkbox" class="custom-control-input" id="estado_revendedores" value="1" {{ old('estado') ==1 ? 'checked' : '' }} name="estado_revendedores">
			<label class="custom-control-label" for="estado_revendedores">Listo para publicar para revendedor</label>
		</div>
	</div>
	<div class="form-group col-lg-8 pl-0">
		<div class="custom-control custom-switch">
            <input type="checkbox" class="custom-control-input" id="destacado" value="1" {{ old('destacado') ==1 ? 'checked' : '' }} name="destacado">
			<label class="custom-control-label" for="destacado">Destacado</label>
		</div>
	</div>
	<div class="form-group col-lg-8 pl-0">
		<div class="custom-control custom-switch">
            <input type="checkbox" class="custom-control-input" id="novedades" value="1" {{ old('novedades') ==1 ? 'checked' : '' }} name="novedades">
			<label class="custom-control-label" for="novedades">Novedades</label>
		</div>
	</div>
	<button type="submit" class="btn btn-success mb-1">Crear Producto</button>
@endsection

resources/views/product/index.blade.php
@extends('layouts.layout')
@section('title', 'Pagina de productos')
@section('content')
    <div class="row justify-content-center">
        @if ($message = Session::get('success'))
            <div class=" col-6  mt-2 alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif

    </div>
    <div class="row justify-content-between m-3">
        <div class="col-lg-3 offset-1">
            <h2 class="font-color-gergal">Productos</h2>
        </div>
        <div class=" col-12 col-lg-2">
            <button style="    background-color: #02934b !important;" class="btn btn-success"
                title="Actualizar masivamente los precios del producto" id="modalOpen">Actualización masiva</button>
        </div>
        <div class="col-lg-3 ">
            <form action="{{ route('productos.filter') }}" method="POST">
                @csrf
                <div class="input-group ">
                    <input type="text" class="form-control" name="nombre" placeholder="Filtrar por nombre o descripción">
                    <div class="input-group-append">
                        <button class="btn btn-gray " type="submit">Filtrar</button>
                    </div>
                </div>
            </form>
        </div>
        @can('product-create')
            <div class="col-lg-2">
                <a href="{{ route('productos.create') }}" type="button" class="btn btn-success-gergal">Crear producto</a>
            </div>
        @endcan
    </div>
    <div class="row justify-content-center">
        <div class="col-12 col-xl-10 table-responsive">
            @if ($productos->isEmpty())
                <p class="lead">No Hay Productos registrados</p>
            @else
                <table class="table table-bordered">
                    <thead>

                        @if (method_exists($productos, 'appends'))
                            <th scope="col">@sortablelink('nombre', 'Nombre')</th>
                            <th scope="col">@sortablelink('descripcion', 'Descripción') </th>
                            <th scope="col">@sortablelink('categoria','Categoría') </th>
                            <th scope="col">@sortablelink('cantidad_en_stock', 'Stock')</th>
                            <th scope="col">@sortablelink('propiedades', 'Propiedades') </th>
                            <th scope="col">@sortablelink('precio_lista', 'Precio de lista') </th>
                            <th scope="col">@sortablelink('precio_revendedor', 'Precio de revendedor') </th>
                            <th scope="col">Precio diferencia</th>
                            <th scope="col">@sortablelink('estado', 'Publicado') </th>
                            <th scope="col"></th>

                        @else
                            <th scope="col">Nombre</th>
                            <th scope="col">Descripción </th>
                            <th scope="col">Categoría </th>
                            <th scope="col">Stock</th>
                            <th scope="col">Propiedades </th>
                            <th scope="col">Precio de lista </th>
                            <th scope="col">Precio de revendedor </th>
                            <th scope="col">Precio diferencia</th>
                            <th scope="col">Publicado</th>
                            <th scope="col"></th>
                        @endif

                    </thead>
                    <tbody>
                        @foreach ($productos as $producto)

                            <tr>
                                <td><a href="{{ route('productos.show', $producto->id) }}">{{ $producto->nombre }}</a>
                                </td>
                                <td>{{ strlen($producto->descripcion) > 120 ? substr($producto->descripcion, 0, 120) . '...' : $producto->descripcion }}
                                </td>
                                <td>{{ empty($producto->categoria) ? '-' : $producto->categoriaR->nombre }}</td>
                                <td>
                                    <p class="form-dblclick" name="{{ 'cantidad_en_stock_' . $producto->id }}">
                                        {{ $producto->cantidad_en_stock ?: '-' }}</p>
                                    <input class="form-control" id="{{ 'cantidad_en_stock_' . $producto->id }}"
                                        type="hidden" name="cantidad_en_stock" value={{ $producto->cantidad_en_stock }}>
                                </td>
                                <td>{{ $producto->propiedades > 120 ? substr($producto->propiedades, 0, 120) . '...' : $producto->propiedades }}
                                </td>
                                </td>
                                <td>

                                    <p class="form-dblclick" name="{{ 'precio_lista_' . $producto->id }}">
                                        {{ $producto->precio_lista }}</p>
                                    <input class="form-control" id="{{ 'precio_lista_' . $producto->id }}" type="hidden"
                                        name="precio_lista" value={{ $producto->precio_lista }}>
                                </td>
                                <td>
                                    <p class="form-dblclick" name="{{ 'precio_revendedor_' . $producto->id }}">
                                        {{ $producto->precio_revendedor }}</p>
                                    <input class="form-control" id="{{ 'precio_revendedor_' . $producto->id }}"
                                        type="hidden" name="precio_revendedor" value={{ $producto->precio_revendedor }}>
                                </td>
                                <td> <span
                                        id="{{ 'percent_' . $producto->id }}">{{ round((1 - (int)substr($producto->precio_revendedor, 1) / (int)substr($producto->precio_lista, 1)) * 100, 2) }}
                                    </span> %</td>
                                <td>{{ $producto->estado ? 'Si' : 'No' }}</td>
                                <td>
                                    @can('product-edit')
                                        <a href="{{ route('productos.edit', $producto->id) }}" type="button"
                                            class="btn btn-outline-primary btn-sm  my-1"> <i class="fas fa-edit"></i></a>
                                    @endcan
                                    {{-- @can('product-delete')
                                        <form name="form-delete" action="{{ route('productos.destroy', $producto->id) }}"
                                            method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-outline-danger btn-sm" disabled><i
                                                    class="fas fa-trash-alt"></i></button>
                                        </form>
                                    @endcan --}}

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
            {{ method_exists($productos, 'appends') ? $productos->appends(\Request::except('page'))->render() : '' }}
        </div>

    </div>

    <div class="modal" id="modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group col-lg-4 pl-0">
                        <label for="percent">Porcentaje de aumento (%)</label>
                        <input type="number" max="100" class="form-control" id="percent" name="percent"
                            aria-describedby='title-feedback'>
                        @error('percent')
                            <div id="percent-feedback" class="is-invalid ">
                                <small class="text-danger">*{{ $message }}</small>
                            </div>
                        @enderror
                    </div>
                    <div class="form-group col-lg-4 pl-0">
                        <label for="percent">Aplicar a</label>
                        <select class="form-control" id="fields" name="fields">
                            <option value="all">Ambos</option>
                            <option value="precio_lista">Precio de lista</option>
                            <option value="precio_revendedor">Precio de revendedor</option>

                        </select>
                        @error('percent')
                            <div id="percent-feedback" class="is-invalid ">
                                <small class="text-danger">*{{ $message }}</small>
                            </div>
                        @enderror
                    </div>
                    <div class="form-group col-lg-4 pl-0">
                        <label for="category">Categoria</label>
                        <select class="form-control" id="category" name="category">
                            <option value="all">Todos</option>
                            @foreach ($categorias as $categoria)
                                <option value="{{ $categoria->id }}"> {{ $categoria->nombre }}</option>
                            @endforeach
                        </select>
                        @error('category')
                            <div id="category-feedback" class="is-invalid ">
                                <small class="text-danger">*{{ $message }}</small>
                            </div>
                        @enderror
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" id="updateBulk">Actualizar</button>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    {{-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous">
    </script> --}}
    <script type="text/javascript">
        $(document).ready(() => {
            const urlBulk = '{{ route('api.producto.update.bulk') }}';

            const modal = $('#modal');
            const button = document.querySelector('#modalOpen');
            const buttonByBulk = document.querySelector('#updateBulk');
            button.addEventListener('click', showModal);
            buttonByBulk.addEventListener('click', sendPostBulk);

            function showModal(evt) {
                modal.modal('show');
            }

            function sendPostBulk() {
                const formData = new FormData();
                const percent = document.querySelector('#percent');
                const fields = document.querySelector('#fields');
                const category = document.querySelector('#category');
                if (!percent.value) {

                    alert('debe agregar un porcentaje');
                    return null;
                }
                if (percent.value > 100) {

                    if (!confirm('Esta agregando un valor mayor a 100, desea continuar?')) {
                        return null;

                    }
                }
                formData.append('percent', percent.value);
                formData.append('fields', fields.value);
                formData.append('category', category.value);
                fetch(urlBulk, {
                        method: 'POST',
                        body: formData,
                    })
                    .then(response => response.json())
                    .then(json => {
                        if (json.status == 'ok') {
                            location.reload();

                        } else {
                            alert('Algo salio mal. intente nuevamente.')
                        }
                    }).catch(error => {
                        alert('Error. no se actualizo el campo.');
                        console.log(error);
                    })

            }

        });
    </script>
@endsection
<script type="text/javascript">
    const url = '{{ route('api.producto.update') }}';
</script>
<script src="{{ asset('js/delete.js') }}" defer></script>
<script src="{{ asset('js/table-edit.js') }}" type="text/javascript" defer>
</script>

resources/views/product/show.blade.php
@extends('layouts.layout')
@section('title', $producto->nombre)
@section('content')
	<div class="row  m-3">
		<div class="col-4 offset-1">
			<h2>{{ $producto->nombre }}</h2>
		</div>

	</div>
	<div class="row justify-content-center mb-5 px-2">
		<div class="col-lg-4 img-effect">
			<div class="text-center">
				<img src="{{ asset(substr($producto->image_path, 6)) }}" class="img-fluid img-hover-hidden"
					alt="{{ $producto->nombre }}">
			</div>
		</div>
		<div class="col-lg-4 img-effect">
			<div class="text-center">
				<img src="{{ asset(substr($producto->hover_image_path, 6)) }}" class="img-fluid img-hover-show"
					alt="{{ $producto->nombre }}">
			</div>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Descripción: {{ $producto->descripcion }}
			</p>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Categoria: {{  empty($producto->categoria)   ? '-' : $producto->categoriaR->nombre }}
			</p>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Sub categoria: {{  empty($producto->subcategoria)   ? '-' : $producto->subcategoria->nombre }}
			</p>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Propiedades: {{ $producto->propiedades }}
			</p>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Información nutricional: {{ $producto->info_nutricional }}
			</p>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Precio de Lista: {{ $producto->precio_lista}}
			</p>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Precio de revendedor: {{ $producto->precio_revendedor }}
			</p>
		</div>
    </div>
    <div class="row justify-content-center">
		<div class="col-8 ">
			<p class="lead">
				Publicado: {{ $producto->estado ? 'Si' : 'No' }}
			</p>
		</div>
	</div>
@endsection