routes/web.php
<?php

use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\ContactoFormController;
use App\Http\Controllers\EstadoController;
use App\Http\Controllers\MinimoCompraController;
use App\Http\Controllers\PedidoController;
use App\Http\Controllers\ProductoController;
use App\Http\Controllers\RecetaController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UsuarioController;
use App\Models\Usuario;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);

    Route::get('productos/filter',[ ProductoController::class, 'filter'])->name('productos.filter.get');
    Route::resource('productos', ProductoController::class)->names('productos');
    Route::post('productos/filter',[ ProductoController::class, 'filter'])->name('productos.filter');
    Route::resource('categorias', CategoriaController::class )->names('categorias');
    Route::post('categorias/filter',[ CategoriaController::class, 'filter'])->name('categorias.filter');
    Route::resource('recetas', RecetaController::class )->names('recetas');
    Route::post('recetas/filter',[ RecetaController::class, 'filter'])->name('recetas.filter');
    Route::resource('usuarios', UsuarioController::class )->names('usuarios');
    Route::post('usuarios/filter',[ UsuarioController::class, 'filter'])->name('usuarios.filter');
    Route::resource('consultas', ContactoFormController::class )->parameters(['consultas' => 'contacto',])->names('consultas');
    Route::post('consultas/filter',[ ContactoFormController::class, 'filter'])->name('consultas.filter');
    Route::get('pedidos/filter',[ PedidoController::class, 'filter'])->name('pedidos.filter.get');
    Route::resource('pedidos', PedidoController::class )->names('pedidos');
    Route::get('pedidos/excel/download/productos/{id}', [ PedidoController::class, 'exportItem'])->name('pedidos.excelItem');
    Route::get('pedidos/excel/download/{days?}/{state?}/{tiposUsuario?}', [ PedidoController::class, 'export'])->where('days', '[0-9]+')->name('pedidos.excel');
    Route::post('pedidos/filter',[ PedidoController::class, 'filter'])->name('pedidos.filter');

    Route::resource('estados', EstadoController::class );
    Route::post('estados/filter',[ EstadoController::class, 'filter'])->name('estados.filter');

	Route::resource('minimo', MinimoCompraController::class)->names('minimo');
    Route::post('minimo/filter',[ MinimoCompraController::class, 'filter'])->name('minimo.filter');


    Route::get('usuario/load', [UsuarioController::class, 'loadAddress']);
});

resources/views/partials/navbar/host/abm.blade.php
<li class="nav-item dropdown">
    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false" v-pre>
        Abm Menu
    </a>

    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

        @can('product-list')
            <a class="dropdown-item" href="{{ route('productos.index') }}">Ver Productos</a>
        @endcan
        @can('recipe-list')
            <a class="dropdown-item" href="{{ route('recetas.index') }}">Ver Recetas</a>
        @endcan
        @can('user-list')
            <a class="dropdown-item" href="{{ route('usuarios.index') }}">Ver Usuarios</a>
        @endcan
        @can('category-list')
            <a class="dropdown-item" href="{{ route('categorias.index') }}">Ver Categorias</a>
        @endcan
        @can('order-list')
            <a class="dropdown-item" href="{{ route('pedidos.index') }}">Ver Pedidos</a>
        @endcan
        @can('order-list')
            <a class="dropdown-item" href="{{ route('estados.index') }}">Ver Estados para pedidos</a>
        @endcan
		@can('minimo-list')
            <a class="dropdown-item" href="{{ route('minimo.index') }}">Ver mínimo de compra</a>
        @endcan
        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
            {{ __('Logout') }}
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
            @csrf
        </form>
    </div>
</li>

resources/views/partials/navbar/host/admin.blade.php
<li class="nav-item dropdown">
    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
        {{ Auth::user()->name }}
    </a>

    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        @can(['product-create'])
            <a class="dropdown-item" href="{{ route('users.index') }}">Gestor Administrativo</a>
        @endcan
        @can('role-create')
            <a class="dropdown-item" href="{{ route('roles.index') }}">Gestor de roles</a>
        @endcan


    </div>
</li>