routes/web.php
<?php

use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\ContactoFormController;
use App\Http\Controllers\EstadoController;
use App\Http\Controllers\MinimoCompraController;
use App\Http\Controllers\PedidoController;
use App\Http\Controllers\ProductoController;
use App\Http\Controllers\RecetaController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UsuarioController;
use App\Models\Usuario;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);

    Route::get('productos/filter',[ ProductoController::class, 'filter'])->name('productos.filter.get');
    Route::resource('productos', ProductoController::class)->names('productos');
    Route::post('productos/filter',[ ProductoController::class, 'filter'])->name('productos.filter');
    Route::resource('categorias', CategoriaController::class )->names('categorias');
    Route::post('categorias/filter',[ CategoriaController::class, 'filter'])->name('categorias.filter');
    Route::resource('recetas', RecetaController::class )->names('recetas');
    Route::post('recetas/filter',[ RecetaController::class, 'filter'])->name('recetas.filter');
    Route::resource('usuarios', UsuarioController::class )->names('usuarios');
    Route::post('usuarios/filter',[ UsuarioController::class, 'filter'])->name('usuarios.filter');
    Route::resource('consultas', ContactoFormController::class )->parameters(['consultas' => 'contacto',])->names('consultas');
    Route::post('consultas/filter',[ ContactoFormController::class, 'filter'])->name('consultas.filter');
    Route::get('pedidos/filter',[ PedidoController::class, 'filter'])->name('pedidos.filter.get');
    Route::resource('pedidos', PedidoController::class )->names('pedidos');
    Route::get('pedidos/excel/download/productos/{id}', [ PedidoController::class, 'exportItem'])->name('pedidos.excelItem');
    Route::get('pedidos/excel/download/{days?}/{state?}/{tiposUsuario?}', [ PedidoController::class, 'export'])->where('days', '[0-9]+')->name('pedidos.excel');
    Route::post('pedidos/filter',[ PedidoController::class, 'filter'])->name('pedidos.filter');

    Route::resource('estados', EstadoController::class );
    Route::post('estados/filter',[ EstadoController::class, 'filter'])->name('estados.filter');

	Route::resource('minimo', MinimoCompraController::class)->names('minimo');
    Route::post('minimo/filter',[ MinimoCompraController::class, 'filter'])->name('minimo.filter');


    Route::get('usuario/load', [UsuarioController::class, 'loadAddress']);
});

app/Models/PedidoItem.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PedidoItem extends Model
{
    use HasFactory;
    protected $table = 'pedidos_items';

    public function pedido (){
        return $this->belongsTo(Pedido::class, 'pedidos_id');
    }

    public function producto(){
        return  $this->belongsTo(Producto::class, 'producto_id');
	}
	public function getProductoPrecioUnitarioAttribute($value){
		return '$'.$value;
	}
}

resources/views/order/create.blade.php
@extends('form.index')
@section('title', 'Crear Producto.')
@section('title-form', 'Crear Producto.')
@section('route-form', route('productos.store'))
@section('content-form')
	<div class="form-group col-lg-4 pl-0">
		<label for="title">Nombre</label>
		<input type="text" class="form-control" id="nombre" name="nombre" aria-describedby='title-feedback'
			value="{{ old('nombre') }}">
		@error('nombre')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group  col-lg-8 pl-0">
		<label for="descripcion">Descripción</label>
		<textarea class="form-control" id="descripcion" name="descripcion" aria-describedby='details-feedback'
			rows="3">{{ old('descripcion') }}</textarea>
		@error('description')
			<div id="details-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-8 pl-0">
		<label for="propiedades">Propiedades</label>
		<textarea class="form-control" id="propiedades" name="propiedades" aria-describedby='details-feedback'
			rows="3">{{ old('propiedades') }}</textarea>
		@error('propiedades')
			<div id="details-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-8 pl-0">
		<label for="info_nutricional">Información nutricional</label>
		<textarea class="form-control" id="info_nutricional" name="info_nutricional" aria-describedby='details-feedback'
			rows="3">{{ old('info_nutricional') }}</textarea>
		@error('info_nutricional')
			<div id="details-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-8 pl-0">
		<label for="img">Imagen del producto</label>
		<input type="file" class="form-control-file" id="img" name="img">
		@error('img')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-8 pl-0">
		<label for="img_hoover">Imagen descriptiva producto</label>
		<input type="file" class="form-control-file" id="img_hoover" name="img_hoover">
		@error('img_hoover')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="categoria">Categoria</label>
		<select class="form-control" name="categoria" id="categoria" required>
			<option disabled selected>--- Seleccione una categoria ---</option>
			@foreach ($categorias as $categoria)
				<option value="{{ $categoria->id }}" {{ old('categoria') == $categoria->id ? 'selected' : '' }}>{{ $categoria->nombre }}</option>
			@endforeach
		</select>
		@error('sub_categoria')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="sub_categoria">Sub categoria</label>
		<select class="form-control" name="sub_categoria" id="sub_categoria" required>
			<option disabled selected>--- Seleccione una sub categoria ---</option>
			@foreach ($categorias as $categoria)
				<option value="{{ $categoria->id }}" {{ old('sub_categoria') == $categoria->id ? 'selected' : '' }}>{{ $categoria->nombre }}</option>
			@endforeach
		</select>
		@error('sub_categoria')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="precio_lista">Precio de lista</label>
		<input type="string" class="form-control" id="precio_lista" name="precio_lista" aria-describedby='title-feedback'
			value="{{ old('precio_lista') }}">
		@error('precio_lista')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-4 pl-0">
		<label for="precio_revendedor">Precio de revendedor</label>
		<input type="string" class="form-control" id="precio_revendedor" name="precio_revendedor"
			aria-describedby='title-feedback' value="{{ old('precio_revendedor') }}">
		@error('precio_revendedor')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>
	<div class="form-group col-lg-8 pl-0">
		<div class="custom-control custom-switch">
            <input type="checkbox" class="custom-control-input" id="estado" value="1" {{ old('estado') ==1 ? 'checked' : '' }} name="estado">
			<label class="custom-control-label" for="estado">Listo para publicar</label>
		</div>
	</div>
	<button type="submit" class="btn btn-success mb-1">Crear Producto</button>
@endsection

resources/views/order/excel.blade.php
<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Pedido</th>
            <th>Usuario</th>
			<th>Dni</th>
            <th>Email</th>
			<th>Telefono</th>
			<th>Codigo de producto</th>
			<th>Producto</th>
			<th>Categoria</th>
			<th>Precio</th>
			<th>Cantidad</th>
			<th>Precio total</th>
			<th>Forma de pago</th>
			<th>Tipo de usuario</th>
			<th>Direccion</th>
			<th>Direccion2</th>
			<th>fecha creado</th>
			<th>Actualizado</th>
			<th>map</th>
			<th>Calle</th>
			<th>Localidad</th>
			<th>Partido</th>
			<th>Provincia</th>
			<th>Barrio</th>
			<th>Pais</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($pedidos as $pedido)

			@foreach ($pedido->productos as $producto)
			<tr>
				<td>{{ $pedido->id }}</td>
				<td>{{ $pedido->usuario->nombre . ' ' . $pedido->usuario->apellido }}</td>
				<td>{{ $pedido->usuario->dni }}</td>
				<td>{{ $pedido->usuario->email }}</td>
				<td>{{ $pedido->usuario->telefono }}</td>
				<td>{{ $producto->id }}</td>
				<td>{{ $producto->nombre }}</td>
				<td>{{ $producto->categoriaR->nombre }}</td>
				<td><p class="currency">{{$producto->pivot->producto_precio_unitario}}</p></td>
				<td>{{$producto->pivot->cant}}</td>
				<td>{{$pedido->precio_total}}</td>
				<td>{{$pedido->forma_pago}}</td>
				<td>{{$pedido->usuario->tipoUsuario->descripcion  }}</td>
				<td>{{$pedido->usuario->direccion }} </td>
				<td>{{$pedido->usuario->direccion2 }} </td>
				<td>{{ $pedido->fecha_creado }}</td>
				<td>{{$pedido->fecha_modif}}</td>
				<td>{{ 'https://maps.google.com/maps?q='.$pedido->usuario->latitud.','.$pedido->usuario->longitud }}</td>
				<td>{{$pedido->usuario->nombre_calle.' '.$pedido->usuario->calle_nro}}</td>
				<td>{{ $pedido->usuario->localidad }}</td>
				<td>{{ $pedido->usuario->partido }}</td>
				<td>{{ $pedido->usuario->provincia }}</td>
				<td>{{ $pedido->usuario->barrio }}</td>
				<td>{{ $pedido->usuario->pais}}</td>
			</tr>
			@endforeach

        @endforeach
    </tbody>
</table>

resources/views/order/excelItem.blade.php
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Categoría </th>
            <th scope="col">Descripción </th>
            <th scope="col">Precio</th>
            <th scope="col">Cantidad </th>
            <th scope="col">Precio Total </th>

        </tr>
    </thead>
    <tbody>
        @foreach ($pedido->productos as $producto)
        <tr>
            <td>{{$producto->nombre}}</td>
            <td>{{$producto->categoriaR->nombre}}</td>
            <td>{{$producto->descripcion}}</td>
            <td><p class="currency">{{$producto->pivot->producto_precio_unitario}}</p></td>
            <td>{{$producto->pivot->cant}}</td>
        </tr>
        @endforeach
        <tr>
            <td colspan="3" >Total</td>

            <td colspan="2"><p class="currency">{{ $pedido->precio_total  }}</p></td>
        </tr>
        <tr>
            <td colspan="2" >Pedido creado: {{ $pedido->fecha_creado }} </td>
            <td colspan="3"></td>
        </tr>
		<tr>
            <td colspan="2" >Pedido Actualizado: {{ $pedido->fecha_creado }} </td>
            <td colspan="3"></td>
        </tr>
        <tr>
            <td colspan="2" >Usuario: {{ $pedido->usuario->nombre.' '.$pedido->usuario->apellido }} </td>
            <td colspan="2" >Dni: {{ $pedido->usuario->dni }} </td>
            <td colspan="3">Email: {{ $pedido->usuario->email }}</td>
        </tr>
		<tr>
			<td colspan="2">Tipo de usuario: {{ $pedido->usuario->tipoUsuario->descripcion }}</td>
			<td colspan="3">Direccion: {{ $pedido->usuario->direccion }}</td>
			<td colspan="3">Direccion de google Map: {{ $pedido->usuario->full_address }}</td>
		</tr>
        @if ($pedido->rev_id)
        <tr>
            <td colspan="2" >usuario intermedario: {{ $pedido->revendedor->nombre.' '.$pedido->revendedor->apellido }} </td>
            <td colspan="3">Email: {{ $pedido->revendedor->email }}</td>
        </tr>
        @endif
    </tbody>
</table>

resources/views/order/index.blade.php
@extends('layouts.layout')
@section('title', 'Pagina de Pedidos')
@section('content')
    <div class="row justify-content-center">
        @if ($message = Session::get('success'))
            <div class=" col-6  mt-2 alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif

    </div>
    <div class="row justify-content-between m-3">
        <div class="col-lg-3 offset-1">
            <h2 class="font-color-gergal">Pedidos</h2>
        </div>
        <div class="col-lg-3 offset-2">
            <form action="{{ route('pedidos.filter') }}" method="POST">
                @csrf
                <div class="input-group ">
                    <input type="text" class="form-control" name="nombre" placeholder="Filtrar por cliente, email o estado">
                    <div class="input-group-append">
                        <button class="btn btn-gray " type="submit">Filtrar</button>
                    </div>
                </div>
            </form>
        </div>

        @can('order-create')
            <div class="col-lg-3  ">
                <div class="form-group col-8">
                    <label for="dias">Dias hacia atras para el reporte</label>
                    <input class="form-control" id="dias" placeholder="cantidad de dias para el reporte" value="30" />
                </div>
                <div class="form-group col-8">
                    <label for="estado">Filtrar estados para reporte</label>
                    <select class="form-control" name="estado" id="estado">
                        <option value="0" selected>Todos</option>
                        @foreach ($estados as $estado)
                            <option value={{ $estado->id }}>{{ $estado->descripcion }}</option>
                        @endforeach
                    </select>
                </div>
				<div class="form-group col-8">
                    <label for="tipo_usuario">Filtrar por tipo de usuario</label>
                    <select class="form-control" name="tipo_usuario" id="tipo_usuario">
                        <option value="0" selected>Todos</option>
                        @foreach ($tiposUsuario as $tiposUsuario)
                            <option value={{ $tiposUsuario->id }}>{{ $tiposUsuario->descripcion}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-8">
                    <a id="download" href="{{ route('pedidos.excel') }}" type="button" class="btn btn-excel-gergal">Descargar
                        listado<i class="fas fa-file-excel"></i></a>
                </div>

            </div>
        @endcan
    </div>
    <div class="row justify-content-center">
        <div class="col-12 col-xl-10 table-responsive">
            @if ($pedidos->isEmpty())
                <p class="lead">No hay pedidos registrados.</p>
            @else
                <table class="table table-bordered">
                    <thead>
                        @if (!method_exists($pedidos, 'render'))
                            <th>Pedido</th>
                            <th>Usuario</th>
                            <th>Creado</th>
                            <th>Actualizado</th>
                            <th>Total</th>
                            <th>Estado</th>
                        @else
                            <th scope="col">@sortablelink('id', 'Pedido' )</th>
                            <th scope="col">@sortablelink('cli_id', 'Usuario')</th>
                            <th scope="col">@sortablelink('fecha_creado','Creado') </th>
                            <th scope="col">@sortablelink('fecha_modif','Actualizado') </th>
                            <th scope="col">@sortablelink('precio_total', 'Total') </th>
                            <th scope="col">@sortablelink('estado', 'Estado') </th>
                        @endif
                        <th scope="col"></th>
                    </thead>
                    <tbody>
                        @foreach ($pedidos as $pedido)
                            <tr>
                                <form id="{{ $pedido->id }}"  dblclick="handlerClick" action="">
                                    <td><a href="{{ route('pedidos.show', $pedido->id) }}">{{ $pedido->id }}</a></td>
                                    <td>{{ $pedido->usuario->nombre . ' ' . $pedido->usuario->apellido }}</td>
                                    <td>{{ $pedido->fecha_creado }}</td>
                                    <td>{{ $pedido->fecha_modif }}</td>
                                    <td>
										<p class="form-dblclick"  name="{{ 'precio_total_' . $pedido->id }}" class="currency" >
										{{ $pedido->precio_total }}</p>

                                    </td>
                                    <td>{{ $pedido->estadoR->descripcion }}</td>

                                </form>
                                <td>
                                    @can('product-edit')
                                        <a href="{{ route('pedidos.edit', $pedido->id) }}" type="button"
                                            class="btn btn-outline-primary btn-sm  my-1"> <i class="fas fa-edit"></i></a>
                                    @endcan
                                    @can('product-delete')
                                        <form name="form-delete" action="{{ route('pedidos.destroy', $pedido->id) }}"
                                            method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button style="pointer-events: none;" type="submit"
                                                class="btn btn-outline-danger btn-sm" disabled><i
                                                    class="fas fa-trash-alt"></i></button>
                                        </form>
                                    @endcan

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
            {{ method_exists($pedidos, 'appends') ? $pedidos->appends(\Request::except('page'))->render() : '' }}

        </div>

    </div>

    <script type="text/javascript">
        const downloadExcel = document.querySelector('#download');
        downloadExcel.addEventListener('click', function() {
            const days = document.querySelector('#dias').value;
            const state = document.querySelector('#estado').value;
            const userType = document.querySelector('#tipo_usuario').value;
            let url = `<?= route('pedidos.excel') ?>/${days}/${state}/${userType}`;
            console.log(url);
            downloadExcel.href = url;

            return false;
        });
    </script>
@endsection
<script src="{{ asset('js/delete.js') }}" defer>
</script>

<script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>

resources/views/order/order.blade.php
@if ($pedido->productos->isEmpty())
    <p class="lead">Sin productos</p>
@else
<div class="row justify-content-between">
    <div class="col-4 ">
        <h4>Producto(s):</h4>
    </div>
    <div class="col-3 offset-3 d-flex justify-content-end">
        <a href="{{ route('pedidos.excelItem', $pedido->id) }}" type="button" class="btn btn-excel-gergal">Descargar listado<i class="fas fa-file-excel"></i></a>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col">
        <table class="table table-bordered">
            <thead>
                <th scope="col">Nombre</th>
                <th scope="col">Categoría </th>
                <th scope="col">Descripción </th>
                <th scope="col">Precio</th>
                <th scope="col">Cantidad </th>
            </thead>
            <tbody>
                @foreach ($pedido->productos as $producto)
                    <tr>
                        <td>{{$producto->nombre}}</td>
                        <td>{{$producto->categoriaR->nombre}}</td>
                        <td>{{$producto->descripcion}}</td>
                        <td><p class="currency">{{$producto->producto_precio_unitario}}</p></td>
                        <td>{{$producto->pivot->cant}}</td>
                    </tr>
                @endforeach
                <tr>
                    <td colspan="3" >Total</td>

                    <td colspan="2"><p class="currency">{{ $pedido->precio_total  }}</p></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@endif

resources/views/order/show.blade.php
@extends('layouts.layout')
@section('title', $pedido->id)
@section('content')
	<div class="row  m-3">
		<div class="col-4 offset-1">
			<h2>Pedido: {{ $pedido->id }}</h2>
		</div>

	</div>
	<div class="row justify-content-start mb-2  ">
		<div class="col-lg-4 offset-2 ">
            <div class="card">
                <div class="card-header">
                    <a href="{{route('usuarios.show',$pedido->usuario->id )}}">Usuario: {{ $pedido->usuario->nombre.' '.$pedido->usuario->apellido }}</a>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Correo electrónico: {{ $pedido->usuario->email }}</li>
                    <li class="list-group-item">Teléfono: {{ $pedido->usuario->telefono }} </li>
                </ul>
            </div>

        </div>

	</div>
    @if ($pedido->rev_id)
    <div class="row justify-content-start mb-2">
        <div class="col-lg-2 offset-2">
            <div class="card">
                <div class="card-header">
                    <a href="{{route('usuarios.show',$pedido->revendedor->id )}}" >Usuario intermedario: {{ $pedido->revendedor->nombre.' '.$pedido->revendedor->apellido }}</a>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Correo electrónico: {{ $pedido->revendedor->email }}</li>
                    <li class="list-group-item">Teléfono: {{ $pedido->revendedor->telefono }}</li>
                </ul>
            </div>
        </div>
    </div>
    @endif

    <div class="row justify-content-center">
        <div class="col-8">
            @include('order.order')
        </div>
    </div>
@endsection

resources/views/order/update.blade.php
@extends('form.index')
@section('title', 'Actualizar pedido.')
@section('title-form', 'Actualizar pedido.')
@section('route-form', route('pedidos.update',$pedido->id))
@section('content-form')
@method('PUT')
<div class="row  ">
    <div class="col-4 ">
        <h2>Pedido: {{ $pedido->fecha_creado }}</h2>
    </div>

</div>
<div class="row justify-content-start mb-2  ">
    <div class="col-lg-2   ">
        <div class="card">
            <div class="card-header">
                <a href="{{route('usuarios.show',$pedido->usuario->id )}}">Cliente: {{ $pedido->usuario->nombre.' '.$pedido->usuario->apellido }}</a>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Correo electrónico: {{ $pedido->usuario->email }}</li>
                <li class="list-group-item">Teléfono: {{ $pedido->usuario->telefono }} </li>
            </ul>
        </div>

    </div>

</div>

	<div class="form-group col-lg-4 pl-0">
        <input type="hidden" name="" id="{{$pedido}}">
		<label for="estado">Estado</label>
		<select class="form-control" name="estado" id="estado" required>
			<option disabled selected>--- Seleccione una Estado ---</option>
			@foreach ($estados as $estado)
				<option value="{{ $estado->id }}" {{ old('estado', $pedido->estado) == $estado->id ? 'selected' : '' }}>{{ $estado->descripcion }}</option>
			@endforeach
		</select>
		@error('sub_categoria')
			<div id="title-feedback" class="is-invalid ">
				<small class="text-danger">*{{ $message }}</small>
			</div>
		@enderror
	</div>

	<button type="submit" class="btn btn-success mb-1">Actualizar Pedido</button>
@endsection